# eureka server
# Request execution error. 
# endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8761/eureka/}, 
#exception=java.net.ConnectException: Connection refused: 
# no further information stacktrace=com.sun.jersey.api.client.ClientHandlerException: 
#java.net.ConnectException: Connection refused: no further information
#  at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
server:
  port: 8761 # fixed
  
  
spring:
  application:
    name: eureka-server